api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter


from api.views import BookReviewAPIView, BookListAPIView, BookReviewListAPIView

app_name = 'api'



urlpatterns = [
    path('books/list/', BookListAPIView.as_view(), name='book-list'),
    path('reviews/<int:id>/', BookReviewAPIView.as_view(), name='review-detail'),
    path('reviews/', BookReviewListAPIView.as_view(), name='review-list'),
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path("admin/", admin.site.urls),
    path("home/", home_page, name='home_page'),
    path('api-auth/', include('rest_framework.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView
from django.urls import path

app_name = 'users'
urlpatterns = [
     path('register/', RegisterView.as_view(), name='register'),
     path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile-update'),

 ]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pictures', null=True, blank=True)

users/forms.py
from django import forms
from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'password']


    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user



class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'profile_picture']

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from users.forms import UserCreateForm, ProfileUpdateForm


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            'form': create_form,
        }

        return render(request, 'users/register.html', context)


    def post(self, request):
        create_form = UserCreateForm(request.POST)

        if create_form.is_valid():
            create_form.save()
            # create user account
            return redirect('users:login')
        else:
            context = {
                'form': create_form,
            }
            return render(request, 'users/register.html', context)



class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()

        context = {
            'login_form': login_form,
        }
        return render(request, 'users/login.html', context)



    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You are now logged in.')

            return redirect('books:list')
        else:
            return render(request, 'users/login.html', {'login_form': login_form})



class LogoutView(LoginRequiredMixin,View):
    def get(self, request):
        logout(request)
        messages.info(request, 'You have been logged out.')
        return redirect('landing_page')



class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'users/profile.html', {'user': request.user})


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = ProfileUpdateForm(instance=request.user)
        return render(request, 'users/profile_edit.html', {'form': user_update_form})

    def post(self, request):
        user_update_form = ProfileUpdateForm(request.POST, instance=request.user, files=request.FILES)
        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, 'You have successfully updated your profile.')
            return redirect('users:profile')
        else:
            return render(request, 'users/profile_edit.html', {'form': user_update_form})

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login page{% endblock %}

{% block content %}

    <h3>Login</h3>

    <div class="row">
        <div class="col-5">
            <form method="post">
     {% csrf_token %}

     {{ login_form | crispy }}

     <button class="btn btn-success" type="submit">Log in </button> <span class="ms-3">No account? Then, <a class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'users:register' %}">get registered</a></span>
 </form>
        </div>
    </div>


{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile page{% endblock %}

{% block content %}


    <div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
        <div class="p-4">
            <div class=" image d-flex flex-column justify-content-center align-items-center">
                <button class="btn btn-secondary">
                    <img src="{{ user.profile_picture.url }}" alt="Profile picture" class="profile-pic">
                </button>
                <p class="name mt-3">{{ user.first_name }} {{ user.last_name }}</p>
                <span class="idd">@{{ user.username }}</span>
                <p>{{ user.email }}</p>

                <div class=" d-flex mt-2">
                    <a class="btn btn-dark" href="{% url 'users:profile-update' %}">edit profile</a>
                </div>

{#                <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center">#}
{#                    <span><i class="fa fa-instagram"></i></span>#}
{#                    <span><i class="fa fa-linkedin"></i></span>#}
{#                </div> <div class=" px-2 rounded mt-4 date ">#}
                <span class="join mt-2">Joined {{ user.date_joined | date:"M d, Y"}}</span>
            </div>
            </div>
        </div>
    </div>


{#    <img src="{{ user.profile_picture.url }}" alt="Profile picture" class="profile-pic">#}
{##}
{#    <div class="mt-3">#}
{#        <a class=" mb-5 link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" href="{% url 'users:profile-update' %}"> edit profile</a>#}
{#    </div>#}
{#    <br>#}
{#    <p class="mt-2">Username: {{ user.username }}</p>#}
{#    <p>First name: {{ user.first_name }}</p>#}
{#    <p>Last name: {{ user.last_name }}</p>#}
{#    <p>Email: {{ user.email }}</p>#}

{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}{% endblock %}

{% block content %}
    <h3>Edit profile</h3>

    <div class="row">
        <div class="col-5">
            <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form | crispy }}
        <button class="btn btn-primary">save changes</button>
        </form>
        </div>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register Page{% endblock %}

{% block content %}
    <h3>Register</h3>

    <div class="row">
        <div class="col-5">
            <form action="{% url 'users:register' %}" method="post">

    {% csrf_token %}

    {{ form | crispy }}

    <button type="submit" class="btn btn-primary">Submit</button>

</form>
        </div>
    </div>


{% endblock %}