api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter


from api.views import BookReviewAPIView, BookListAPIView, BookReviewListAPIView

app_name = 'api'



urlpatterns = [
    path('books/list/', BookListAPIView.as_view(), name='book-list'),
    path('reviews/<int:id>/', BookReviewAPIView.as_view(), name='review-detail'),
    path('reviews/', BookReviewListAPIView.as_view(), name='review-list'),
]

books/urls.py
from books.views import BooksView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView
from django.urls import path


app_name = 'books'


urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/review/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name='edit-review'),
    path('<int:book_id>/reviews/<int:review_id>/confirm-delete/', ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(), name='delete-review'),
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path("admin/", admin.site.urls),
    path("home/", home_page, name='home_page'),
    path('api-auth/', include('rest_framework.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView
from django.urls import path

app_name = 'users'
urlpatterns = [
     path('register/', RegisterView.as_view(), name='register'),
     path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile-update'),

 ]

templates/base.html
{% load static %}
{% url 'home_page' as home_page_url%}
{% url 'books:list' as books_page_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile-update' as edit_profile_page %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Goodreads Clone {% endblock %}</title>
</head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

<body class="m-5">

<nav class="navbar navbar-expand-lg mb-3" style="background-color: #e3f2fd;" data-bs-theme="light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads clone</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
        </li>
          <li class="nav-item">
          <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{{ books_page_url }}">Books</a>
        </li>


      </ul>
      <div class="nav-item">
          {% if request.user.is_authenticated %}
              <div>
                  <ul class="navbar-nav">
                      <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == edit_profile_page %} active {% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ request.user.username }}
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ profile_page_url }}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                      </ul>
                  </li>
                  </ul>
              </div>
          {% else %}
              <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Log in</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>



{% if messages %}

    {% for message in messages %}
        <div class=" m-2 alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}

{% endif %}

{% block content %}  {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>


</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

    <h3>Home page</h3>
    {% for review in page_obj %}

        <div class="container posts-content">
            <div class="row">
                <div class="col-lg-4">
                    <div class="card mb-4">
                      <div class="card-body">
                        <div class="media mb-3">
                          <img src="{{ review.user.profile_picture.url}}" class="d-block ui-w-40 rounded-circle" alt="">
                          <div class="media-body ml-3">
                              {{ review.user.username}}
                            <div class="text-muted small">{{ review.created_at | date:"M d, Y" }}</div>
                          </div>
                        </div>

                        <p>{{ review.comment | truncatechars:300}}</p>

                          <a href="{% url 'books:detail' review.book.id %}"><img src="{{ review.book.cover_picture.url }}" class="cover-pic center"></a>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    <nav aria-label="...">
          <ul class="pagination">
              {% if page_obj.has_previous %}
                 <li class="page-item">
                    <a class="page-link" href="{% url 'home_page' %}?page={{ page_obj.previous_page_number }}">previous</a>
                 </li>

              {% else %}
                  <li class="page-item disabled">
                    <a class="page-link">previous</a>
                 </li>

              {% endif %}

            <li class="page-item active">
              <a class="page-link" href="#" aria-current="page">{{ page_obj.number }}</a>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'home_page' %}?page={{ page_obj.next_page_number }}">next</a>
                </li>
            {% endif %}
          </ul>
        </nav>

{% endblock %}

templates/landing.html
{% extends 'base.html' %}

{% block content %}
    <h1>Landing page!</h1>

    <p>
        Goodreads is an American social cataloging website operated by Goodreads, Inc., a subsidiary of Amazon.
        Users can search its database of books, annotations, quotes, and reviews and expand the database by registering books to generate
        library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions.
        The website's offices are located in San Francisco.[2]


    </p>

{% endblock %}